'use client';

import { useEffect, useMemo, useState } from 'react';

type Result = { id?: string; subject: string; summary: string; draft: string; reviewed: string; grade?: string; student?: string; created_at?: string };
const initialSubjects = ['국어', '수학', '영어'];
const sample: Result[] = [
  { subject: '국어', summary: '토론 자료를 근거와 쟁점 중심으로 구조화하고, 자신의 관점을 문장으로 정리함.', draft: '수업에서 다룬 주제에 대해 관련 자료의 핵심 내용을 비교·분석하고 토론 과정에서 근거를 들어 자신의 의견을 논리적으로 표현함.', reviewed: '수업에서 다룬 주제에 대해 관련 자료의 핵심 내용을 비교·분석하고 토론 과정에서 근거를 들어 자신의 의견을 논리적으로 표현함.' },
  { subject: '수학', summary: '실생활 자료에서 변수를 찾고 여러 풀이 과정을 검토함.', draft: '실생활 자료를 수학적으로 해석하는 활동에 참여하여 변수 사이의 관계를 식으로 나타내고 풀이 과정을 설명함.', reviewed: '실생활 자료를 수학적으로 해석하는 활동에 참여하여 변수 사이의 관계를 식으로 나타내고 풀이 과정을 설명함.' },
];

export default function Home() {
  const [tab, setTab] = useState<'create'|'history'|'settings'>('create');
  const [student, setStudent] = useState(''); const [grade, setGrade] = useState('고등학교 2학년');
  const [subjects, setSubjects] = useState(initialSubjects); const [subject, setSubject] = useState('국어');
  const [keywords, setKeywords] = useState(''); const [results, setResults] = useState<Result[]>([]); const [history, setHistory] = useState<Result[]>([]);
  const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false); const [notice, setNotice] = useState('');
  const [apiKey, setApiKey] = useState(''); const [model, setModel] = useState('gemini-3.5-flash-lite');
  useEffect(() => { setApiKey(localStorage.getItem('geminiKey') || ''); setModel(localStorage.getItem('geminiModel') || 'gemini-3.5-flash-lite'); }, []);
  const total = useMemo(() => results.length, [results]);
  async function generate() {
    if (!keywords.trim()) { setNotice('학생 활동 키워드나 관찰 내용을 입력해 주세요.'); return; }
    setBusy(true); setNotice('3개 에이전트가 활동 기록을 정리하고 있습니다…'); setSaved(false);
    try { const r = await fetch('/api/generate', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ student, grade, subjects, keywords, apiKey, model }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setResults(data.results); setNotice('수집 → 작성 → 검토 에이전트 작업이 완료되었습니다.'); }
    catch (e) { setResults(subjects.map((s) => ({ subject:s, summary:'입력 내용을 핵심 활동·과정·배움 중심으로 정리했습니다.', draft:`${s} 수업에서 ${keywords.trim()} 활동에 참여하여 관련 자료를 탐색하고 자신의 과정을 설명함. 활동 과정에서 관찰한 내용을 근거로 생각을 정리하며 교과 개념을 실제 맥락에 연결함.`, reviewed:`${s} 수업에서 ${keywords.trim()} 활동에 참여하여 관련 자료를 탐색하고 자신의 과정을 설명함. 활동 과정에서 관찰한 내용을 근거로 생각을 정리하며 교과 개념을 실제 맥락에 연결함.` }))); setNotice('연결된 생성 API가 없어 안전한 로컬 초안으로 표시했습니다.'); }
    finally { setBusy(false); }
  }
  async function saveAll() { setBusy(true); try { const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student,grade,keywords,results})}); if(!r.ok) throw new Error(); setSaved(true); setNotice('Supabase에 과목별 결과를 저장했습니다.'); loadHistory(); } catch { setNotice('Supabase 연결 정보를 확인해 주세요.'); } finally { setBusy(false); } }
  async function loadHistory() { try { const r=await fetch('/api/records'); const d=await r.json(); if(r.ok) setHistory(d.records || []); } catch {} }
  useEffect(() => { if(tab==='history') loadHistory(); }, [tab]);
  function download(r:Result) { const blob=new Blob([`세특 초안 · ${r.subject}\n\n${r.reviewed}`],{type:'text/plain;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`세특_${r.subject}.txt`; a.click(); }
  return <main><header><div className="brand"><span className="logo">S</span><div><b>세특 스튜디오</b><small>학생 성장 기록을 문장으로</small></div></div><nav><button className={tab==='create'?'active':''} onClick={()=>setTab('create')}>새로 작성</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>저장 내역</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>개인 메뉴</button></nav><span className="avatar">교사</span></header>
  {tab==='create' && <><section className="hero"><div><p className="eyebrow">AI 기록 파트너</p><h1>학생의 과정을<br/><em>성장의 문장</em>으로</h1><p className="lead">키워드와 관찰 내용을 입력하면<br/>과목별 세부능력 및 특기사항 초안을 작성합니다.</p></div><div className="agent-card"><div className="orbit">✦</div><p>3-에이전트 워크플로우</p><div className="agent-row"><span>01</span><b>수집</b><i>→</i><span>02</span><b>작성</b><i>→</i><span>03</span><b>검토</b></div><small>사실 기반 · 과정 중심 · 규정 점검</small></div></section>
  <section className="workspace"><div className="panel form-panel"><div className="panel-head"><div><span className="step">01</span><h2>학생 활동 기록</h2></div><span className="required">* 필수 항목</span></div><label>학생 식별값 <span>*</span><input value={student} onChange={e=>setStudent(e.target.value)} placeholder="예: 2026-021" /></label><div className="two"><label>학년 <select value={grade} onChange={e=>setGrade(e.target.value)}><option>고등학교 1학년</option><option>고등학교 2학년</option><option>고등학교 3학년</option></select></label><label>대표 과목 <select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label></div><label>대상 과목 <div className="chips">{subjects.map(s=><button key={s} className="chip selected" onClick={()=>setSubjects(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}>{s} ×</button>)}<button className="chip add" onClick={()=>{const n=prompt('과목 이름'); if(n && !subjects.includes(n)){setSubjects([...subjects,n]);setSubject(n)}}}>+ 과목 추가</button></div></label><label>키워드 또는 관찰 내용 <span>*</span><textarea value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="학생의 활동, 질문, 탐구 과정, 협업 모습 등을 자유롭게 입력해 주세요." /><small className="hint">구체적인 행동과 과정을 적을수록 문장이 풍부해집니다.</small></label><button className="primary" onClick={generate} disabled={busy}>{busy?'작성 중…':'✦  세특 초안 생성하기'}</button></div>
  <div className="panel result-panel"><div className="panel-head"><div><span className="step lavender">02</span><h2>과목별 결과</h2></div>{total>0 && <span className="count">{total}개 과목</span>}</div>{results.length===0?<div className="empty"><div className="empty-icon">✧</div><h3>아직 생성된 결과가 없습니다</h3><p>왼쪽에 학생 활동 내용을 입력하고<br/>초안 생성하기를 눌러 시작하세요.</p></div>:<div className="results">{results.map(r=><article className="result" key={r.subject}><div className="result-title"><div><span className="subject-dot">●</span><h3>{r.subject}</h3></div><button onClick={()=>download(r)}>↓ TXT</button></div><div className="summary"><b>수집 요약</b><p>{r.summary}</p></div><p className="draft">{r.reviewed}</p></article>)}<div className="save-box"><span>✓</span><div><b>검토가 완료된 문장입니다</b><small>학생 식별값·학년·과목·생성일시와 함께 저장됩니다.</small></div><button onClick={saveAll} disabled={busy||saved}>{saved?'저장됨':'Supabase에 저장'}</button></div></div>}</div></section><p className="notice">{notice}</p></>}
  {tab==='history' && <section className="page"><div className="page-title"><p className="eyebrow">ARCHIVE</p><h1>저장 내역</h1><p>Supabase에 저장된 과거 세특 초안을 다시 확인합니다.</p></div>{history.length===0?<div className="empty large"><div className="empty-icon">▤</div><h3>저장된 기록이 없습니다</h3><p>새 결과를 생성하고 저장하면 이곳에서 확인할 수 있습니다.</p></div>:<div className="history-list">{history.map((r:any)=><article className="history-card" key={r.id}><div><span className="pill">{r.subject}</span><h3>{r.student_identifier} · {r.grade}</h3><small>{new Date(r.created_at).toLocaleString('ko-KR')}</small></div><p>{r.reviewed_text}</p></article>)}</div>}</section>}
  {tab==='settings' && <section className="page settings"><div className="page-title"><p className="eyebrow">PERSONAL MENU</p><h1>개인 메뉴</h1><p>생성에 사용할 Gemini 연결 정보를 이 브라우저에 저장합니다.</p></div><div className="settings-card"><label>Gemini API Key<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="AIza…" /><small>키는 서버 생성 요청에만 사용되며, 저장 시 브라우저 localStorage에 보관됩니다.</small></label><label>선호 모델<select value={model} onChange={e=>setModel(e.target.value)}><option value="gemini-3.5-flash-lite">Gemini 3.5 Flash-Lite (기본)</option><option value="gemini-2.5-flash">Gemini 2.5 Flash</option><option value="gemini-2.5-pro">Gemini 2.5 Pro</option></select></label><button className="primary" onClick={()=>{localStorage.setItem('geminiKey',apiKey);localStorage.setItem('geminiModel',model);setNotice('개인 설정을 저장했습니다.');}}>설정 저장하기</button><p className="privacy">API 키는 외부에 표시되지 않도록 입력란이 가려져 있습니다. 실제 배포에서는 사용자 인증과 암호화된 서버 저장을 권장합니다.</p></div></section>}</main>
}
