'use client'
import {useState} from 'react'
const data:Record<string,[string,string][]>={
  '환경·기후':[['학교 주변 미세먼지는 시간대에 따라 어떻게 달라질까?','센서 데이터를 직접 수집해 교내 공기질을 분석해보세요.'],['우리 학교의 일회용품 사용량을 줄일 수 있을까?','일주일간 사용량을 조사하고 실천 전후를 비교해보세요.']],
  '과학·기술':[['스마트폰 사용 시간은 수면의 질에 영향을 줄까?','간단한 설문과 수면 기록으로 상관관계를 살펴보세요.'],['교실의 소음은 집중력에 어떤 영향을 줄까?','소음의 크기와 과제 수행 시간을 비교해보세요.']],
  '사회·문화':[['우리 반의 뉴스 소비 방식은 어떻게 다를까?','매체별 신뢰도와 이용 습관을 인터뷰해보세요.'],['학교 공간은 모두에게 편리할까?','친구들의 동선을 관찰해 더 나은 공간을 제안해보세요.']],
  '언어·미디어':[['짧은 영상의 제목은 시청 의도에 영향을 줄까?','같은 내용의 제목을 바꿔 반응을 비교해보세요.'],['온라인 댓글의 말투는 어떻게 달라지고 있을까?','주제별 댓글을 분류해 언어 특징을 찾아보세요.']],
  '예술·디자인':[['색의 온도감은 공간의 인상을 바꿀까?','색 조합을 활용해 선호도와 감정 변화를 조사해보세요.']],
  '건강·생활':[['아침 식사는 오전 수업 집중도와 관계가 있을까?','식사 여부와 자기 평가 집중도를 기록해보세요.'],['공부할 때 듣는 음악은 기억에 영향을 줄까?','음악 조건별 단어 기억 개수를 비교해보세요.']]
}
export default function Page(){const [sel,setSel]=useState<string[]>([]);const [show,setShow]=useState(false);const [saved,setSaved]=useState<string[]>([]);const cards=sel.flatMap(k=>data[k].map(([title,desc])=>({k,title,desc}))).slice(0,6);return <><header className="topbar"><a className="brand" href="#top"><span className="brand-mark">✳</span>탐구의 첫 문장</a><nav><a href="#explore">주제 찾기</a><a href="#how">탐구 가이드</a><span>저장한 주제 <small>{saved.length}</small></span></nav></header><main id="top"><section className="hero"><div className="eyebrow">RESEARCH TOPIC EXPLORER <span>01</span></div><h1>좋은 탐구는<br/><em>좋은 질문</em>에서 시작돼.</h1><p className="hero-copy">막연한 관심사를 교과와 연결해<br/>나만의 탐구 주제로 바꿔보세요.</p><a className="primary-btn" href="#explore">내 주제 찾기 <span>↗</span></a><div className="hero-note"><span className="dot"/> 3분이면 충분해요 · 정답은 없어요</div></section><section className="explore" id="explore"><div className="section-intro"><div className="eyebrow">START HERE <span>02</span></div><h2>요즘, 무엇이<br/>궁금한가요?</h2><p>가장 끌리는 키워드를 골라주세요.<br/>선택을 바탕으로 탐구 방향을 제안해드릴게요.</p></div><div className="topic-picker"><div className="picker-head"><span>01 / 관심 분야</span><span>{sel.length?`${sel.length}개 선택됨`:'복수 선택 가능'}</span></div><div className="chips">{Object.keys(data).map(k=><button className={`chip ${sel.includes(k)?'selected':''}`} onClick={()=>setSel(sel.includes(k)?sel.filter(x=>x!==k):[...sel,k])} key={k}>{k}</button>)}</div><button className="recommend-btn" disabled={!sel.length} onClick={()=>setShow(true)}>선택한 키워드로 주제 보기 <span>→</span></button></div></section>{show&&<section className="results show"><div className="results-head"><div><div className="eyebrow">YOUR QUESTIONS <span>03</span></div><h2>이런 질문은 어때요?</h2></div><button className="text-btn" onClick={()=>{setShow(false);setSel([])}}>다시 고르기 ↻</button></div><div className="result-grid">{cards.map((c,i)=><article className="card" key={c.title}><span className="card-tag">{String(i+1).padStart(2,'0')} / {c.k}</span><h3>{c.title}</h3><p>{c.desc}</p><button className={`save ${saved.includes(c.title)?'saved':''}`} onClick={()=>setSaved(saved.includes(c.title)?saved.filter(x=>x!==c.title):[...saved,c.title])}>{saved.includes(c.title)?'♥ 저장됨':'♡ 주제 저장하기'}</button></article>)}</div></section>}<section className="guide" id="how"><div className="eyebrow">FROM QUESTION TO PROJECT <span>04</span></div><h2>질문을 발견했다면,<br/>이제 탐구를 설계할 차례.</h2><div className="steps">{[['01','관찰하기','주변의 현상에서\n작은 변화를 찾아보세요.'],['02','좁혀보기','누구를, 언제, 어떻게\n살펴볼지 정해보세요.'],['03','검증하기','자료를 모으고\n나만의 답을 만들어보세요.']].map(([n,t,p])=><div key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></div>)}</div></section></main><footer><span>✳ 탐구의 첫 문장</span><span>나의 호기심을 연구로</span></footer></>}
